### ISSUE TITLE
It is not running after install 

### ISSUE THREAD

**Issue by asvany** [ferrislucas/promptr#10]
install: 
```
# npm install -g @ifnotnowwhen/promptr
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'commander@10.0.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'liquidjs@10.7.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }

added 16 packages, and audited 17 packages in 2s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

$sb_release -a
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

$ promptr
```
file:///usr/local/lib/node_modules/@ifnotnowwhen/promptr/bin/index.js:3
await MainService.call()
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

```

**Comment by ferrislucas** [comment]
Hi @asvany, thanks for creating this issue. It looks like you're on node 12, but promptr requires node 14 or greater. If you're able to upgrade node then that should solve this issue. I'm looking at ways to incorporate a binary so that node 14 won't be required.

**Comment by ferrislucas** [comment]
Closing this issue - I hope to add binaries to the releases soon so node version won’t be an issue at that time.

**Comment by ferrislucas** [comment]
@asvany you should be able to use promptr if you’re on macOS. Please try placing the `promptr` binary from this release in your path:
https://github.com/ferrislucas/promptr/releases/tag/v3.0.2
